---
apiVersion: garden.io/v1
kind: Project
name: spring-boot-garden
dotIgnoreFile: .gitignore

variables:
  logLevel: DEBUG

  replicas: 1
  autoscaling:
    enabled: false

  kubernetes-providers-config:
    context: arn:aws:eks:us-east-2:346163573116:cluster/uniphore-dev-us-eks-platform
    defaultHostname: us.cloud.uniphoredev.com
    buildMode: cluster-buildkit
    imagePullSecrets:
      - name: uniphore-secret
      - name: dockerhub-secret
    deploymentRegistry:
      hostname: registry.uniphore.com
      namespace: uniphore

defaultEnvironment: dev
environments:
  - name: dev
    defaultNamespace: ${replace(local.usernameLowerCase,'.','-')}

  - name: ci
    defaultNamespace: ${project.name}-${local.env.GITHUB_RUN_ID}

  - name: build
    defaultNamespace: build

providers:
  - name: jib
  - name: kubernetes
    environments:
      - dev
      - ci
      - build
    $merge: ${var.kubernetes-providers-config}
    namespace:
      name: ${environment.namespace}
  - name: kubernetes
    environments:
      - dev
    deploymentRegistry:
      hostname: registry.uniphore.com
      namespace: uniphore-manual
