---
kind: Module
type: helm
name: hello-world-java

serviceResource:
  kind: Deployment
  name: hello-world-java
  containerModule: hello-world-java-image

build:
  dependencies:
    - name: hello-world-java-image

values:
  logLevel: ${var.logLevel}

  image:
    id: ${modules.hello-world-java-image.outputs.deployment-image-id}

  replicaCount: ${var.replicas}
  autoscaling:
    enabled: ${var.autoscaling.enabled}

  ingress:
    hostName: api-${providers["kubernetes"].config.namespace.name}
    domainName: ${providers["kubernetes"].config.defaultHostname}

  datadog:
    env: dev-${replace(local.usernameLowerCase,'.','-')}
