apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../base
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
      name: hello-world-java
