apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: spring-boot-garden
spec:
  releaseName: spring-boot-garden
  chart:
    spec:
      chart: spring-boot-garden
      sourceRef:
        kind: HelmRepository
        name: uniphore-oci-charts
        namespace: flux-system
      version: "0.1.0-v0cfda265"
  interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    logLevel: INFO
    image:
      id: "registry.uniphore.com/uniphore/spring-boot-garden:v-65a31d1396"
    replicaCount: 3
    ingress:
      hostName: api
      domainName: ${INGRESS_DOMAIN_NAME}
      certName: ${CERT_NAME}
    datadog:
      env: ""
    oidc:
      issuer: ""
