---
kind: Module
type: helm
name: spring-boot-garden

serviceResource:
  kind: Deployment
  name: spring-boot-garden
  containerModule: spring-boot-garden-image

build:
  dependencies:
    - name: spring-boot-garden-image

values:
  logLevel: ${var.logLevel}

  image:
    id: ${modules.spring-boot-garden-image.outputs.deployment-image-id}

  replicaCount: ${var.replicas}
  autoscaling:
    enabled: ${var.autoscaling.enabled}

  ingress:
    hostName: api-${providers["kubernetes"].config.namespace.name}
    domainName: ${providers["kubernetes"].config.defaultHostname}

  datadog:
    env: dev-${replace(local.usernameLowerCase,'.','-')}
