{{- if .Values.ingress.enabled }}
{{- $fullName := include "hello-world-java.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "hello-world-java.labels" . | nindent 4 }}
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: hello-world-java-cors, hello-world-java-claims, hello-world-java-oidc
    {{- include "hello-world-java.ingress.annotations" . | nindent 4 }}
spec:
  ingressClassName: kong
  {{- include "hello-world-java.ingress.tls" . | nindent 2 }}
  rules:
    - host: {{ .Values.ingress.hostName }}.{{ .Values.ingress.domainName }}
      http:
        paths:
          - path: /hello-world-java
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
{{- end }}
