apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: spring-boot-garden
spec:
  releaseName: spring-boot-garden
  targetNamespace: platform
  values:
    datadog:
      env: staging
    oidc:
      issuer: https://dev-g2j5mu2z.us.auth0.com/.well-known/openid-configuration
