apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-boot-garden.fullname" . }}
  labels:
    {{- include "spring-boot-garden.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | required "replicaCount required" }}
  selector:
    matchLabels:
      {{- include "spring-boot-garden.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spring-boot-garden.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: default
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.id }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi

          env:
            - name: APP_PORT
              value: {{ .Values.service.port | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
          ports:
            - name: http
              containerPort: {{ .Values.service.port | required "service.port required" }}
          startupProbe:
            httpGet:
              path: /health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
