{{- if .Values.ingress.enabled }}
{{- $fullName := include "spring-boot-garden.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "spring-boot-garden.labels" . | nindent 4 }}
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: spring-boot-garden-cors, spring-boot-garden-claims, spring-boot-garden-oidc
    {{- include "spring-boot-garden.ingress.annotations" . | nindent 4 }}
spec:
  ingressClassName: kong
  {{- include "spring-boot-garden.ingress.tls" . | nindent 2 }}
  rules:
    - host: {{ .Values.ingress.hostName }}.{{ .Values.ingress.domainName }}
      http:
        paths:
          - path: /spring-boot-garden
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
{{- end }}
