apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: spring-boot-garden-cors
plugin: cors
config:
  origins:
    - "*"
  methods:
    - GET
    - POST
    - HEAD
    - PUT
    - PATCH
    - DELETE
  headers:
    - "*"
  credentials: true
  max_age: 3600
  preflight_continue: false
