apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-garden.fullname" . }}
  labels:
    {{- include "spring-boot-garden.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.port | required "service.port required" }}
  selector:
    {{- include "spring-boot-garden.selectorLabels" . | nindent 4 }}
