---
name: Auto Merge Dependabot PR
"on":
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
jobs:
  CI:
    if: github.actor == 'dependabot[bot]'
    uses: ./.github/workflows/cicd.yml
    secrets: inherit
  Dependabot-Automerge:
    needs: CI
    uses: uniphore/platform-github-actions/.github/workflows/dependabot-automerge.yml@main
    secrets: inherit
