---
name: Pull Request Labeler
"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - ready_for_review
jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v5
